modules: !Imports
    - buildbot-docker-build
    - buildbot-kubernetes-deploy

branches:
    master:
        push: [ build, test, deploy ]
        pr: [ build, test ]
stages:
    build:
        worker:
            type: docker
            image: workerbase
        steps:
            - !DockerBuild
                dockerfile: Dockerfile
                image_name: myapp

            - !DockerUploadNexus
                image_name: !i "myapp:%(prop:buildid)s"
    test:
        worker:
            type: docker
            image: workerbase
        steps:
            - !Git
                 repourl: !i "%(prop:repository)s"
                 codebase: !i "%(prop:codebase)s"
            - !WithKubernetesInfra
                specs: k8s_staging/*.yml
                template_args:
                    buildid: !i "%(prop:buildid)s"
                steps:
                    - k8s_staging/test_e2e.sh

    deploy:
        worker:
            type: docker
            image: workerbase
        steps:
            - !DeployKubernetes
                specs: k8s_prod/*.yml
                template_args:
                    buildid: !i "%(prop:buildid)s"
